# Generated by Django 5.0.6 on 2024-07-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_comment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
